---
- hosts: k8s-clients:k8s-cluster
  tasks:
    - name: "create .kube directory"
      file:
        path: "/home/{{ ansible_user }}/.kube"
        state: directory

    - name: "Copy admin kube config file to node"
      copy:
        src: "{{ inventory_dir }}/artifacts/admin.conf"
        dest: "/home/{{ ansible_user }}/.kube/config"
        owner: "{{ ansible_user }}"

    - name: Copy kubectl binary to client
      copy:
        src: "{{ inventory_dir }}/artifacts/kubectl"
        dest: "{{ bin_dir }}/kubectl"
        mode: 0755
      become: yes
