---
- name: look up docker cgroup driver
  shell: "docker info | grep 'Cgroup Driver' | awk -F': ' '{ print $2; }'"
  register: docker_cgroup_driver_result
  changed_when: false
  when: container_manager in ['crio', 'docker', 'rkt']

- name: set standalone_kubelet fact
  set_fact:
    standalone_kubelet: >-
      {%- if inventory_hostname in groups['kube-master'] and inventory_hostname not in groups['kube-node'] -%}true{%- else -%}false{%- endif -%}

- name: set kubelet_cgroup_driver_detected fact for containerd
  set_fact:
    kubelet_cgroup_driver_detected: >-
      {%- if containerd_use_systemd_cgroup -%}systemd{%- else -%}cgroupfs{%- endif -%}
  when: container_manager == 'containerd'

- name: set kubelet_cgroup_driver_detected fact for other engines
  set_fact:
    kubelet_cgroup_driver_detected: "{{ docker_cgroup_driver_result.stdout }}"
  when: container_manager in ['crio', 'docker', 'rkt']

- name: os specific vars
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_release }}.yml"
        - "{{ ansible_distribution|lower }}-{{ ansible_distribution_major_version|lower|replace('/', '_') }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
      skip: true

- name: set variables for calculation dynamic_kubelet_max_pods
  set_fact:
    cpu_weight: 0.5
    memory_weight: 0.5
    ## m5.2xlarge as base
    cpu_const: 4
    memory_const: 31117

- name: Calcucalate possible value of kubelet_max_pods
  set_fact:
    dynamic_kubelet_max_pods: "{{ (((ansible_memtotal_mb / memory_const * cpu_weight) + (ansible_processor_cores / cpu_const * memory_weight)) * kubelet_max_pods)| int }}"

- name: Ensure that dynamic_kubelet_max_pods not less than {{ kubelet_max_pods }}
  set_fact:
    dynamic_kubelet_max_pods: "{{ kubelet_max_pods }}"
  when: kubelet_max_pods > dynamic_kubelet_max_pods
