- name: Create external_admin.conf
  shell: sed 's#server:.*#server:\ https://{{ hostvars[inventory_hostname]['ansible_default_ipv4']['address'] }}:6443#g' /etc/kubernetes/admin.conf  > /etc/kubernetes/external_admin.conf
  become: true

- name: restart kubelet
  service:
    name: kubelet
    state: restarted